name: AXI IO-PMP Tests
on:
  pull_request:
    branches: [master]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 12
      - run: |
          source setup_env.sh
          cd tb/
          make
