name: AXI IO-PMP Tests
on: [push, pull_request]
jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source setup_env.sh
          cd tb/
          make
